---
language: c
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    compiler: gcc
  - os: linux
    dist: trusty
    sudo: false
    compiler: clang
  - os: osx
    osx_image: xcode8.3
    compiler: clang
  allow_failures:
  - os: osx
addons:
  apt:
    packages:
      - python-docutils
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install docutils; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nghttp2 ; fi
  - ./autogen.sh
  - ./configure
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PYTHONPATH=`brew --prefix`/lib/python2.7/site-packages; fi
  - make -j3 check VERBOSE=1
